# Generated by Django 2.1.3 on 2019-10-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
                ('salary', models.CharField(max_length=30)),
                ('dept', models.CharField(max_length=10)),
            ],
        ),
    ]
